name: ci

on: [push, pull_request]

jobs:
  vim_tests:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Tests
      run: bash test/run_test.sh
